package org.jpa.app.compositeKeys;

import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;

/*
* EmbeddableId fields will be saved in the database in the entity table with same names as mentioned in Embeddable class.
* Embedded ids cannot be generated even with @GeneratedValue annotation
* Composite primary keys cannot be generated by hibernate
 * */

@Entity
public class Company {

    @EmbeddedId
    private EmbeddableId ids;
    private String name;

    public EmbeddableId getIds() {
        return ids;
    }

    public void setIds(EmbeddableId ids) {
        this.ids = ids;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
