package org.jpa.app.compositeKeys;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.SequenceGenerator;

// @IdClass annotation is used to specify the composite primary key class
// Both the fields will be represented as the columns in the entity table
// Composite primary keys cannot be generated by hibernate

@Entity
@IdClass(DepartmentId.class)
public class Department {

    @Id
    @SequenceGenerator(name = "id_seq", allocationSize = 30, sequenceName = "id_seq", schema = "public")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_seq")
    private int id;

    @Id
    private String code;

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }
}
